package com.algo.strings;

// A String is a subsequence of a given String, that is generated by deleting some character of a given string
// without changing its order.


import java.util.ArrayList;
import java.util.List;

public class Subsequence {

    public static void main(String[] args) {
        String str = "abc";
        List<String> subsequences = printSubsequence(str);
        subsequences.forEach(e -> System.out.println(e));

    }

    private static List<String> printSubsequence(String str) {

        List<String> subsequences = new ArrayList<>();
        printSubsequenceHelper(str, "", subsequences);
        return subsequences;

    }

    private static void printSubsequenceHelper(String strInput, String strOutput, List<String> subsequences) {

        if (strInput.length() == 0) {
            subsequences.add(strOutput);
            // System.out.println(strOutput);
            return;
        }
        //do not include character in output
        printSubsequenceHelper(strInput.substring(1), strOutput, subsequences);
        //include character in output
        printSubsequenceHelper(strInput.substring(1), strOutput + strInput.charAt(0), subsequences);


    }
}
