package com.algo.strings;

// A String is a subsequence of a given String, that is generated by deleting some character of a given string
// without changing its order.

public class Subsequence {

    public static void main(String[] args){
        String str="abc";
        printSubsequence(str);
    }

    private static void printSubsequence(String str) {

        printSubsequenceHelper(str,"");
    }

    private static void printSubsequenceHelper(String strInput,String strOutput) {

       if(strInput.length()==0){
           System.out.println(strOutput);
           return;
       }
       //do not include character in output
        printSubsequenceHelper(strInput.substring(1),strOutput);
       //include character in output
        printSubsequenceHelper(strInput.substring(1),strOutput+strInput.charAt(0));


    }
}
